// ─────────────────────────────────────────────────────────────────
// TRAINER LIST — edit this file to add/remove/reorder trainers
// Format: { n: "Name", s: "SplitName" }
// ─────────────────────────────────────────────────────────────────
const TRAINERS = [
// ── Roark ──────────────────────────────────────────────
{n:"Before First Battle",s:"Roark"},
{n:"Youngster Tristan",s:"Roark"},
{n:"Lass Natalie",s:"Roark"},
{n:"Bug Catcher Logan",s:"Roark"},
{n:"Clowns",s:"Roark"},
{n:"School Kid Harrison",s:"Roark"},
{n:"School Kid Christine",s:"Roark"},
{n:"Lass Samantha",s:"Roark"},
{n:"Youngster Tyler",s:"Roark"},
{n:"Lass Sarah",s:"Roark"},
{n:"Barry #2",s:"Roark"},
{n:"Youngster Dallas",s:"Roark"},
{n:"Youngster Michael",s:"Roark"},
{n:"Bug Catcher Sebastian",s:"Roark"},
{n:"Lass Kaitlin",s:"Roark"},
{n:"Lass Madeline",s:"Roark"},
{n:"Camper Curtis",s:"Roark"},
{n:"Picnicker Diana",s:"Roark"},
{n:"Worker Mason (Gauntlet Start)*",s:"Roark"},
{n:"Worker Colin (Gauntlet End)*",s:"Roark"},
{n:"Scientist Jonathon",s:"Roark"},
{n:"Ruin Maniac Darius",s:"Roark"},
{n:"Leader Roark",s:"Roark"},
// ── Gardenia ───────────────────────────────────────────
{n:"Galactic Venus & Galactic Luna",s:"Gardenia"},
{n:"Twins Liv & Liz (DOUBLE, Gauntlet Start)*",s:"Gardenia"},
{n:"Bug Catcher Brandon (Gauntlet)*",s:"Gardenia"},
{n:"Aroma Lady Taylor (Gauntlet End)*",s:"Gardenia"},
{n:"Galactic Mercury (B2B With Galactic Terra)",s:"Gardenia"},
{n:"Galactic Terra (B2B With Galactic Mercury)",s:"Gardenia"},
{n:"Galactic Pluto (DOUBLE)",s:"Gardenia"},
{n:"Team Galactic Squad Deimos",s:"Gardenia"},
{n:"Team Galactic Squad Phobos",s:"Gardenia"},
{n:"Commander Mars (DOUBLE)",s:"Gardenia"},
{n:"Camper Jacob",s:"Gardenia"},
{n:"Hiker Daniel",s:"Gardenia"},
{n:"Aroma Lady Elizabeth",s:"Gardenia"},
{n:"Picnicker Siena",s:"Gardenia"},
{n:"Camper Zackary",s:"Gardenia"},
{n:"Hiker Nicholas",s:"Gardenia"},
{n:"Picnicker Karina",s:"Gardenia"},
{n:"Battle Girl Kelsey",s:"Gardenia"},
{n:"Trainer Cheryl (TAG PARTNER)",s:"Gardenia"},
{n:"Galactic Ophelia & Galactic Bianca",s:"Gardenia"},
{n:"Galactic Setebos & Galactic Sycorax",s:"Gardenia"},
{n:"Galactic Prospero & Galactic Miranda",s:"Gardenia"},
{n:"Galactic Puck (Next to the sign)",s:"Gardenia"},
{n:"Galactic Trinculo (Bottom right corner)",s:"Gardenia"},
{n:"Galactic Mercury (Above Trinculo)",s:"Gardenia"},
{n:"Galactic Venus (Above the trees)",s:"Gardenia"},
{n:"Galactic Uranus & Galactic Francisco",s:"Gardenia"},
{n:"Galactic Triton & Galactic Neptune",s:"Gardenia"},
{n:"Galactic Terra & Galactic Luna",s:"Gardenia"},
{n:"Fisherman Joseph",s:"Gardenia"},
{n:"Fisherman Andrew",s:"Gardenia"},
{n:"Fisherman Zachary",s:"Gardenia"},
{n:"Lass Caroline",s:"Gardenia"},
{n:"Aroma Lady Jenna",s:"Gardenia"},
{n:"Artist Angel",s:"Gardenia"},
{n:"Leader Gardenia",s:"Gardenia"},
// ── Fantina ────────────────────────────────────────────
{n:"Galactic Amalthia (Gauntlet Start)*",s:"Fantina"},
{n:"Scientist Galileo (Gauntlet End)*",s:"Fantina"},
{n:"Galactic Callisto (Gauntlet Start)*",s:"Fantina"},
{n:"Galactic Europa (Gauntlet End)*",s:"Fantina"},
{n:"Galactic Ganymede (Gauntlet Start)*",s:"Fantina"},
{n:"Galactic Io (Gauntlet End)*",s:"Fantina"},
{n:"Commander Jupiter",s:"Fantina"},
{n:"Cyclist Axel & Cyclist John",s:"Fantina"},
{n:"Cyclist Megan & Cyclist Nicole",s:"Fantina"},
{n:"Cyclist James",s:"Fantina"},
{n:"Cyclist Rachel",s:"Fantina"},
{n:"Cyclist Ryan",s:"Fantina"},
{n:"Cyclist Karen",s:"Fantina"},
{n:"Roughneck Robert",s:"Fantina"},
{n:"Pokefan Stewart",s:"Fantina"},
{n:"Blackbelt Kyle",s:"Fantina"},
{n:"Aroma Lady Hannah",s:"Fantina"},
{n:"Hiker Alexander",s:"Fantina"},
{n:"Hiker Jonathan",s:"Fantina"},
{n:"Dragon Tamer Drax",s:"Fantina"},
{n:"Artist William",s:"Fantina"},
{n:"Ninja Boy Donny (FOG)",s:"Fantina"},
{n:"Policeman Morton (FOG)",s:"Fantina"},
{n:"Psychic Tony (FOG, Also Room 5)",s:"Fantina"},
{n:"Idol Catherine",s:"Fantina"},
{n:"Clown Chance (RIGHT SIDE)",s:"Fantina"},
{n:"Clown Luigi",s:"Fantina"},
{n:"Artist Allen",s:"Fantina"},
{n:"Idol Amber",s:"Fantina"},
{n:"Leader Fantina (Room 5 Separate Fight)",s:"Fantina"},
{n:"Ninja Boy Drew (FOG, Also Room 5)",s:"Fantina"},
{n:"Clown Justin (FOG, Also Room 5)",s:"Fantina"},
{n:"Psychic Helen (FOG)",s:"Fantina"},
{n:"Policeman Kevin (FOG, Also Room 5)",s:"Fantina"},
{n:"Psychic Theodore (FOG)",s:"Fantina"},
{n:"Clown Luigi (Also Room 2)",s:"Fantina"},
{n:"Idol Catherine (FOG)",s:"Fantina"},
{n:"Ninja Boy Donny (FOG) #2",s:"Fantina"},
{n:"Psychic Cheyenne (FOG)",s:"Fantina"},
{n:"Leader Fantina",s:"Fantina"},
// ── Maylene ────────────────────────────────────────────
{n:"Barry #3 (Chimchar)",s:"Maylene"},
{n:"Barry #3 (Piplup)",s:"Maylene"},
{n:"Barry #3 (Turtwig)",s:"Maylene"},
{n:"Pkmn Breeder Albert",s:"Maylene"},
{n:"Jogger Richard",s:"Maylene"},
{n:"Twins Emma & Lil (DOUBLE BATTLE)",s:"Maylene"},
{n:"Poké Kid Danielle",s:"Maylene"},
{n:"Pkmn Breeder Jennifer",s:"Maylene"},
{n:"Jogger Raul (OPTIONAL)",s:"Maylene"},
{n:"Cowgirl Shelley",s:"Maylene"},
{n:"Young Couple Ty & Sue (DOUBLE BATTLE)",s:"Maylene"},
{n:"Rancher Marco",s:"Maylene"},
{n:"Jogger Wyatt (OPTIONAL)",s:"Maylene"},
{n:"Belle & Pa Ava & Matt (DOUBLE BATTLE)",s:"Maylene"},
{n:"Pkmn Breeder Johnny",s:"Maylene"},
{n:"Gambler John Keating (SUPERBOSS)*",s:"Maylene"},
{n:"Ruin Maniac Calvin (RAIN)",s:"Maylene"},
{n:"Cyclist Cecelia (RAIN)",s:"Maylene"},
{n:"Twins Teri & Tia (DOUBLE BATTLE, RAIN)",s:"Maylene"},
{n:"Rancher Gregory (RAIN)",s:"Maylene"},
{n:"Blackbelt Derek (RAIN)",s:"Maylene"},
{n:"Jogger Scott (OPTIONAL, RAIN)",s:"Maylene"},
{n:"Beauty Jasmine",s:"Maylene"},
{n:"Double Team Nate & Lisa (DOUBLE BATTLE)",s:"Maylene"},
{n:"Galactic Uranus (TAG BATTLE)",s:"Maylene"},
{n:"Galactic Cupid (TAG BATTLE)",s:"Maylene"},
{n:"Battle Girl Carly",s:"Maylene"},
{n:"Blackbelt Daniel",s:"Maylene"},
{n:"Roughneck Rafael",s:"Maylene"},
{n:"Battle Girl Jedrzejczyk",s:"Maylene"},
{n:"BirdKeeper Kahlil",s:"Maylene"},
{n:"Roughneck Magnus",s:"Maylene"},
{n:"Leader Maylene",s:"Maylene"},
// ── Wake ───────────────────────────────────────────────
{n:"Psychic Abigail (MULTI BATTLE)",s:"Wake"},
{n:"Psychic Mitchell (MULTI BATTLE)",s:"Wake"},
{n:"Gambler Carlos",s:"Wake"},
{n:"Ruin Maniac Bryan",s:"Wake"},
{n:"Collector Ripper",s:"Wake"},
{n:"Beauty Cyndy",s:"Wake"},
{n:"Ruin Maniac Jones",s:"Wake"},
{n:"Collector Brady",s:"Wake"},
{n:"Interviewers Molly & Shannon (DOUBLE BATTLE)",s:"Wake"},
{n:"BirdKeeper Billie (MULTI BATTLE)",s:"Wake"},
{n:"Ruin Maniac Bruno (MULTI BATTLE)",s:"Wake"},
{n:"Sailor Gene (MULTI BATTLE)",s:"Wake"},
{n:"PokéKid Jerry (MULTI BATTLE)",s:"Wake"},
{n:"Guitarist Kenny (MULTI BATTLE)",s:"Wake"},
{n:"Idol Dolly (MULTI BATTLE)",s:"Wake"},
{n:"Beauty Britney (MULTI BATTLE)",s:"Wake"},
{n:"Dragon Tamer Elton (MULTI BATTLE)",s:"Wake"},
{n:"Double Team Stevie & Lindsey (DOUBLE BATTLE)",s:"Wake"},
{n:"Tuber Jared (OPTIONAL)*",s:"Wake"},
{n:"Tuber Chelsea (OPTIONAL)*",s:"Wake"},
{n:"Swimmer Mary (GAUNTLET START)*",s:"Wake"},
{n:"Swimmer Sheltin (GAUNTLET)*",s:"Wake"},
{n:"Swimmer Haley (GAUNTLET)*",s:"Wake"},
{n:"Fisherman Kenneth (GAUNTLET)*",s:"Wake"},
{n:"Sailor Paul (GAUNTLET END)*",s:"Wake"},
{n:"Beauty Chelle",s:"Wake"},
{n:"PKMN Breeder Frank (OPTIONAL)",s:"Wake"},
{n:"Barry #4 (Chimchar, Pastoria Gym)",s:"Wake"},
{n:"Barry #4 (Piplup, Pastoria Gym)",s:"Wake"},
{n:"Barry #4 (Turtwig, Pastoria Gym)",s:"Wake"},
{n:"Roughneck Walter",s:"Wake"},
{n:"Fisherman Josh",s:"Wake"},
{n:"Tuber Jacky",s:"Wake"},
{n:"Parasol Lady Monet",s:"Wake"},
{n:"Tuber Caitlyn",s:"Wake"},
{n:"Pkmn Ranger Erick",s:"Wake"},
{n:"Leader Crasher Wake",s:"Wake"},
// ── Byron ──────────────────────────────────────────────
{n:"Galactic Io",s:"Byron"},
{n:"Policeman Bobby",s:"Byron"},
{n:"Lady Melissa",s:"Byron"},
{n:"Rich Boy Jason",s:"Byron"},
{n:"Socialite Reina",s:"Byron"},
{n:"Gentleman Jeremy",s:"Byron"},
{n:"Artist Alexander",s:"Byron"},
{n:"Gambler Nicky",s:"Byron"},
{n:"Beauty Elle",s:"Byron"},
{n:"Lady Celeste",s:"Byron"},
{n:"Socialite Scarlet",s:"Byron"},
{n:"Policeman Caleb",s:"Byron"},
{n:"Rich Boy Liam",s:"Byron"},
{n:"Waiter Affogato (Left Side)",s:"Byron"},
{n:"Waiter Doppio (Right Side)",s:"Byron"},
{n:"Gentleman Butler",s:"Byron"},
{n:"Policeman Danny",s:"Byron"},
{n:"Pkmn Ranger Jeffery",s:"Byron"},
{n:"Pkmn Ranger Taylor",s:"Byron"},
{n:"Galactic Luna (FOG)",s:"Byron"},
{n:"Galactic Valetudo (FOG, OPTIONAL)",s:"Byron"},
{n:"Galactic Terra (FOG)",s:"Byron"},
{n:"Galactic Venus (FOG)",s:"Byron"},
{n:"Galactic Leda (FOG, DOUBLE BATTLE)",s:"Byron"},
{n:"Galactic Amalthia (FOG)",s:"Byron"},
{n:"Galactic Metis (FOG)",s:"Byron"},
{n:"Galactic Themisto (FOG, DOUBLE BATTLE)",s:"Byron"},
{n:"Galactic Dia (FOG, OPTIONAL)*",s:"Byron"},
{n:"Galactic Thebe (FOG)",s:"Byron"},
{n:"Galactic Himalia (FOG)",s:"Byron"},
{n:"Galactic Callisto (FOG)",s:"Byron"},
{n:"Galactic Europa (FOG)",s:"Byron"},
{n:"Galactic Pluto (FOG)",s:"Byron"},
{n:"Galactic Ganymede (FOG)",s:"Byron"},
{n:"Galactic Io (FOG, DOUBLE BATTLE)",s:"Byron"},
{n:"Commander Jupiter (FOG, DOUBLE BATTLE)",s:"Byron"},
{n:"Galactic Mercury",s:"Byron"},
{n:"Leader Cyrus (FOG)",s:"Byron"},
{n:"Worker Dillan",s:"Byron"},
{n:"Worker Holden",s:"Byron"},
{n:"Worker Conrad",s:"Byron"},
{n:"Barry #5 (Chimchar, Canalave Bridge)",s:"Byron"},
{n:"Barry #5 (Piplup, Canalave Bridge)",s:"Byron"},
{n:"Barry #5 (Turtwig, Canalave Bridge)",s:"Byron"},
{n:"Pkmn Trainer Riley (TAG PARTNER)",s:"Byron"},
{n:"Galactic Calypso (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Thalassa (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Despina (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Galatea (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Hippocamp (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Psamanthe (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Naid (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Nereid (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Halimede (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Proteus (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Sao (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Neso (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Larissa (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Laomedeia (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Triton (MULTI BATTLE)",s:"Byron"},
{n:"Galactic Neptune (MULTI BATTLE)",s:"Byron"},
{n:"Sailor Cesar",s:"Byron"},
{n:"Scientist Bill",s:"Byron"},
{n:"Idol Skylar",s:"Byron"},
{n:"Hiker David",s:"Byron"},
{n:"Leader Byron",s:"Byron"},
// ── Candice ────────────────────────────────────────────
{n:"Trainer Marley (PARTNER)",s:"Candice"},
{n:"Galactic Pan (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Daphnis (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Epimetheus (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Prometheus (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Phoebe (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Iapetus (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Enceladus (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Mimas (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Pandora (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Dione (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Atlas (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Hyperion (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Tethys (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Rhea (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Commander Saturn (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Titan (RAIN, MULTI BATTLE)",s:"Candice"},
{n:"Galactic Mercury (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Venus (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Luna (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Pluto (MULTI BATTLE)",s:"Candice"},
{n:"Commander Mars (MULTI BATTLE)",s:"Candice"},
{n:"Galactic Terra (MULTI BATTLE)",s:"Candice"},
{n:"Blackbelt Philip (HAIL)",s:"Candice"},
{n:"Guitarist Garrett (HAIL)",s:"Candice"},
{n:"Ninja Boy Ethan (OPTIONAL, HAIL)",s:"Candice"},
{n:"Blackbelt Luke (OPTIONAL, HAIL)",s:"Candice"},
{n:"Ninja Boy Matthew (OPTIONAL, HAIL)",s:"Candice"},
{n:"Leader Candice (HAIL)",s:"Candice"},
// ── Volkner ────────────────────────────────────────────
{n:"Guitarist Cole (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"BirdKeeper Nicola (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Rich Boy Trey (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Policeman Thomas (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Belle & Pa Scout & Atticus (SUN, DOUBLE BATTLE)",s:"Volkner"},
{n:"Aroma Lady Carolina (SUN)",s:"Volkner"},
{n:"Pokefan Sheen (SUN DOUBLES)",s:"Volkner"},
{n:"Sailor Jack (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Lady Rose (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Interviewers Barbara & Walter (SUN, DOUBLE)",s:"Volkner"},
{n:"Socialite Alec (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Gentleman Luther (SUN, MULTI BATTLE)",s:"Volkner"},
{n:"Tuber Holly (SUN, OPTIONAL)",s:"Volkner"},
{n:"Pokefan RJ (MULTI BATTLE)",s:"Volkner"},
{n:"Clown Forrest",s:"Volkner"},
{n:"Cowgirl Meghan",s:"Volkner"},
{n:"Worker Hugh (MULTI BATTLE)",s:"Volkner"},
{n:"Waiter Reynolds (MULTI BATTLE)",s:"Volkner"},
{n:"Psychic Destiny",s:"Volkner"},
{n:"Gambler Ace",s:"Volkner"},
{n:"Guitarist Preston",s:"Volkner"},
{n:"Leader Volkner (Double Battle)",s:"Volkner"},
// ── Galactic HQ ────────────────────────────────────────
{n:"Pkmn Ranger Jeffrey",s:"Galactic"},
{n:"Pkmn Ranger Allison",s:"Galactic"},
{n:"Pkmn Ranger Taylor",s:"Galactic"},
{n:"Swimmer Wang (RAIN, OPTIONAL)* A",s:"Galactic"},
{n:"Swimmer Wang (RAIN, OPTIONAL)* B",s:"Galactic"},
{n:"Swimmer Wang (RAIN, OPTIONAL)* C",s:"Galactic"},
{n:"Swimmer Wang (RAIN, OPTIONAL)* D",s:"Galactic"},
{n:"Fisherman Greg (DOUBLE BATTLE)",s:"Galactic"},
{n:"Collector Gerald (MULTI BATTLE, GAUNTLET)*",s:"Galactic"},
{n:"Clown Bob (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Camper Parker (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Bug Catcher Adalbert (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Camper Mike (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Lass Cassidy (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Youngster Butch (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Hiker Reginald (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Hiker Lorenzo (MULTI BATTLE, GAUNTLET)",s:"Galactic"},
{n:"Scientist Caliban",s:"Galactic"},
{n:"Galactic Portia (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Cressida (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Trinculo",s:"Galactic"},
{n:"Galactic Umbriel (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Francisco (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Miranda (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Ferdinand (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Margaret (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Cupid (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Setebos (MULTI BATTLE, Up)*",s:"Galactic"},
{n:"Galactic Sycorax (MULTI BATTLE, Up)*",s:"Galactic"},
{n:"Galactic Ariel (MULTI BATTLE, Right)*",s:"Galactic"},
{n:"Galactic Bianca (MULTI BATTLE, Right)*",s:"Galactic"},
{n:"Galactic Rosalind",s:"Galactic"},
{n:"Galactic Bebhionn (OPTIONAL Top Trainer)",s:"Galactic"},
{n:"Galactic Erripaus (OPTIONAL Right Trainer)",s:"Galactic"},
{n:"Galactic Janus",s:"Galactic"},
{n:"Scientist Stephano (Optional Top Path)*",s:"Galactic"},
{n:"Galactic Oberon (Optional Bottom, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Puck (Optional Bottom, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Prospero",s:"Galactic"},
{n:"Galactic Alborix (Right Door, OPTIONAL)",s:"Galactic"},
{n:"Galactic Skymir (Right Door, OPTIONAL)",s:"Galactic"},
{n:"Galactic Loge (Right Door, OPTIONAL)",s:"Galactic"},
{n:"Galactic Hyperion (Left Door, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Prometheus (Left Door, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Tethys (Middle Door, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Dione (Middle Door, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Titan",s:"Galactic"},
{n:"Galactic Epimetheus (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Pandora (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Enceladus (Up, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Mimas (Up, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Daphnis (Middle, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Pan (Middle, MULTI BATTLE)*",s:"Galactic"},
{n:"Galactic Kari (Path 1)*",s:"Galactic"},
{n:"Galactic Geirrod (MULTI BATTLE, Path 1)",s:"Galactic"},
{n:"Galactic Greip (MULTI BATTLE, Path 1)",s:"Galactic"},
{n:"Galactic Iapetus (Up, MULTI BATTLE, Path 2)*",s:"Galactic"},
{n:"Galactic Phoebe (MULTI BATTLE, Path 2)",s:"Galactic"},
{n:"Galactic Atlas (Path 2)",s:"Galactic"},
{n:"Galactic Rhea (OPTIONAL, Path 2)",s:"Galactic"},
{n:"Galactic Uranus",s:"Galactic"},
{n:"Leader Cyrus (Trick Room)",s:"Galactic"},
{n:"Galactic Io",s:"Galactic"},
{n:"Commander Saturn",s:"Galactic"},
{n:"Galactic Ganymede (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Halimede (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Despina (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Bianca (MULTI BATTLE, HQ)",s:"Galactic"},
{n:"Galactic Ferdinand (Upstairs)",s:"Galactic"},
{n:"Galactic Rosalind (In the grass)",s:"Galactic"},
{n:"Galactic Valetudo",s:"Galactic"},
{n:"Galactic Cupid (Rock Smash, MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Cressida (Rock Smash, MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Cordelia (Cut Split)",s:"Galactic"},
{n:"Galactic Puck",s:"Galactic"},
{n:"Trainer Cheryl (TAG PARTNER)",s:"Galactic"},
{n:"Galactic Oberon (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Titania (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Proteus",s:"Galactic"},
{n:"Galactic Laomedeia (OPTIONAL)",s:"Galactic"},
{n:"Galactic Larissa",s:"Galactic"},
{n:"Trainer Riley (TAG PARTNER)",s:"Galactic"},
{n:"Galactic Terra (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Luna (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Europa",s:"Galactic"},
{n:"Galactic Pluto",s:"Galactic"},
{n:"Galactic Prospero #2",s:"Galactic"},
{n:"Galactic Miranda (Strength + Rock Smash Path)",s:"Galactic"},
{n:"Galactic Angrboda (Strength + Cut Path)",s:"Galactic"},
{n:"Galactic Ariel (Split)",s:"Galactic"},
{n:"Galactic Umbriel (Split)",s:"Galactic"},
{n:"Galactic Callisto (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Hippocamp (MULTI BATTLE)",s:"Galactic"},
{n:"Trainer Marley (TAG PARTNER)",s:"Galactic"},
{n:"Galactic Neptune (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Triton (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Mercury (MULTI BATTLE)",s:"Galactic"},
{n:"Galactic Venus (MULTI BATTLE)",s:"Galactic"},
{n:"Barry (TAG PARTNER, Chimchar)",s:"Galactic"},
{n:"Barry (TAG PARTNER, Piplup)",s:"Galactic"},
{n:"Barry (TAG PARTNER, Turtwig)",s:"Galactic"},
{n:"Commander Mars (MULTI BATTLE)",s:"Galactic"},
{n:"Commander Jupiter (MULTI BATTLE)",s:"Galactic"},
// ── Elite Four ─────────────────────────────────────────
{n:"Swimmer Miranda",s:"Elite Four"},
{n:"Swimmer Aubree",s:"Elite Four"},
{n:"Swimmer Paige",s:"Elite Four"},
{n:"Swimmer Wesley",s:"Elite Four"},
{n:"Sailor Zachariah",s:"Elite Four"},
{n:"Swimmer Francisco",s:"Elite Four"},
{n:"Swimmer Ledecky",s:"Elite Four"},
{n:"Roughneck Wyatt",s:"Elite Four"},
{n:"Blackbelt Roku",s:"Elite Four"},
{n:"Beauty Jasmine",s:"Elite Four"},
{n:"Aroma Lady Fadel",s:"Elite Four"},
{n:"Collector Tobias",s:"Elite Four"},
{n:"Clown Julia",s:"Elite Four"},
{n:"Hiker J.J Ahern",s:"Elite Four"},
{n:"Bug Catcher Ford",s:"Elite Four"},
{n:"Ruin Maniac Greg",s:"Elite Four"},
{n:"Idol Zoe",s:"Elite Four"},
{n:"Dragon Tamer Clinton",s:"Elite Four"},
{n:"Barry #6 (Chimchar)",s:"Elite Four"},
{n:"Barry #6 (Piplup)",s:"Elite Four"},
{n:"Barry #6 (Turtwig)",s:"Elite Four"},
];

// ─────────────────────────────────────────────────────────────────
// SPLIT COLOURS — add new splits here when you add new split names
// ─────────────────────────────────────────────────────────────────
const SPLITS_CFG = {
  "Roark":      {color:"#BA7517", bg:"rgba(186,117,23,0.2)"},
  "Gardenia":   {color:"#3B7A1A", bg:"rgba(59,122,26,0.2)"},
  "Fantina":    {color:"#8B3FA8", bg:"rgba(139,63,168,0.2)"},
  "Maylene":    {color:"#B03060", bg:"rgba(176,48,96,0.2)"},
  "Wake":       {color:"#1E6FCC", bg:"rgba(30,111,204,0.2)"},
  "Byron":      {color:"#0F8E6A", bg:"rgba(15,142,106,0.2)"},
  "Candice":    {color:"#3A9ECC", bg:"rgba(58,158,204,0.2)"},
  "Volkner":    {color:"#B8A010", bg:"rgba(184,160,16,0.2)"},
  "Galactic":   {color:"#CC3A3A", bg:"rgba(204,58,58,0.2)"},
  "Elite Four": {color:"#7A40CC", bg:"rgba(122,64,204,0.2)"},
};

const ATT_COLORS = [
  "#4e79a7","#e15759","#edc948","#f28e2b","#59a14f",
  "#76b7b2","#af7aa1","#ff9da7","#9c755f","#bab0ac",
  "#6ea6d4","#f5a9a9"
];
